// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDH3PA36UjBS0_0j2RWp1GwyxOzfrwHWNA',
    appId: '1:879320012130:android:ea7f7a3abf5e4402d8083b',
    messagingSenderId: '879320012130',
    projectId: 'shree-krishna-emb',
    storageBucket: 'shree-krishna-emb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4p5-QTEHRrJxIRwLCcPqToN4fSPX6ncs',
    appId: '1:879320012130:ios:94f3300b15949cfbd8083b',
    messagingSenderId: '879320012130',
    projectId: 'shree-krishna-emb',
    storageBucket: 'shree-krishna-emb.firebasestorage.app',
    androidClientId:
        '879320012130-fjot0jajuvac7e77gfu1764p7c3052uu.apps.googleusercontent.com',
    iosClientId:
        '879320012130-l27pn2odufibdl8g8si5f2pjr9v0c0ua.apps.googleusercontent.com',
    iosBundleId: 'com.example.shreeKrishnaEmbAdmin',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvtoGKeocf0SYsQg1SYZJP0pv8zkn8iUg',
    appId: '1:879320012130:web:faf2d7b99c6f1630d8083b',
    messagingSenderId: '879320012130',
    projectId: 'shree-krishna-emb',
    authDomain: 'shree-krishna-emb.firebaseapp.com',
    storageBucket: 'shree-krishna-emb.firebasestorage.app',
  );
}
